from random import randint
n1 = randint(0, 9)
n2 = randint(0, 9)
n3 = randint(0, 9)
n4 = randint(0, 9)
n5 = randint(0, 9)
lista = (n1, n2, n3, n4, n5)
print('\nOs valores sorteados foram', end=' ')
print(f'{lista[0]} {lista[1]} {lista[2]} {lista[3]} {lista[4]}')
print(f'O maior valor sorteado foi {sorted(lista)[4]}')
print(f'O menor valor sorteado foi {sorted(lista)[0]}')
